### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by Mihai-github** [enzonotario/lighthouse-laravel-websockets#12]
Hi,
   
   Nice work you've done here, but i am wondering if there is a other way to support subscription with lighthouse because is so much work to be done to make it work and there must be a way implemented by them.. or should be 👍 
   Also I am wondering if you can tell me.. from what i've checked you trigger a subscription from web/routes.php (home page) by clicking on that button, but you can can make that mutation that you have created work in playground?

**Comment by enzonotario** [comment]
Hi! You can use any driver you want. This is just an example over `laravel-websockets`. I don't think that Lighthouse has to implement every driver, but there may exist packages that implements some drivers. The problem is that this repo is just an example, not a package that implements the `laravel-websockets` driver. So you have to follow this as a tutorial.
Definitly, if it were a package that implements the `laravel-websocket` driver, it would be so much easily to install it. Maybe someday I will work on that.

> Also I am wondering if you can tell me.. from what i've checked you trigger a subscription from web/routes.php (home page) by clicking on that button, but you can can make that mutation that you have created work in playground?

It's triggered from [`triggerTestSubscription` mutation](https://github.com/enzonotario/lighthouse-laravel-websockets/blob/222531f198a4722ad9928f39aa7e96474071b6d9/app/GraphQL/Mutations/TriggerTestSubscriptionMutation.php#L13), but you can trigger that in any other place. It should work (if you also follow `laravel-websockets` instructions).
